-- Server-authoritative access plans for paid subject practice.
-- Prices are stored in Supabase; browser values are never accepted.

CREATE TABLE IF NOT EXISTS public.subject_pricing_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_days integer NOT NULL,
    price numeric(10,2) NOT NULL,
    currency_code text NOT NULL DEFAULT 'INR',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT subject_pricing_plans_duration_check
        CHECK (duration_days IN (15, 30, 60, 90)),
    CONSTRAINT subject_pricing_plans_price_check CHECK (price >= 0),
    CONSTRAINT subject_pricing_plans_duration_unique UNIQUE (duration_days)
);

INSERT INTO public.subject_pricing_plans (duration_days, price, currency_code)
VALUES
    (15, 99.00, 'INR'),
    (30, 149.00, 'INR'),
    (60, 249.00, 'INR'),
    (90, 349.00, 'INR')
ON CONFLICT (duration_days) DO NOTHING;

REVOKE ALL ON TABLE public.subject_pricing_plans
FROM PUBLIC, anon, authenticated, service_role;

ALTER TABLE public.cart_items
    ADD COLUMN IF NOT EXISTS pricing_plan_id bigint,
    ADD COLUMN IF NOT EXISTS duration_days integer;

ALTER TABLE public.cart_items
    DROP CONSTRAINT IF EXISTS cart_items_pricing_plan_fk;

ALTER TABLE public.cart_items
    ADD CONSTRAINT cart_items_pricing_plan_fk
    FOREIGN KEY (pricing_plan_id)
    REFERENCES public.subject_pricing_plans(id);

ALTER TABLE public.cart_items
    DROP CONSTRAINT IF EXISTS cart_items_duration_check;

ALTER TABLE public.cart_items
    ADD CONSTRAINT cart_items_duration_check
    CHECK (duration_days IN (15, 30, 60, 90));

CREATE OR REPLACE FUNCTION public.get_subject_pricing_plans()
RETURNS TABLE (
    plan_id bigint,
    duration_days integer,
    price numeric,
    currency_code text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
    SELECT id, duration_days, price, currency_code
    FROM public.subject_pricing_plans
    WHERE is_active = true
    ORDER BY duration_days;
$function$;

REVOKE ALL ON FUNCTION public.get_subject_pricing_plans()
FROM PUBLIC, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_subject_pricing_plans()
TO authenticated;

CREATE OR REPLACE FUNCTION public.add_subject_to_cart(
    p_subject_id bigint,
    p_duration_days integer
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
    v_user_id uuid := auth.uid();
    v_cart_id uuid;
    v_plan public.subject_pricing_plans%ROWTYPE;
    v_currency_code text;
BEGIN
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Sign in before adding a subject to your cart.';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = v_user_id AND status = 'active'
    ) THEN
        RAISE EXCEPTION 'Your account is not active.';
    END IF;

    SELECT * INTO v_plan
    FROM public.subject_pricing_plans
    WHERE duration_days = p_duration_days AND is_active = true;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'The selected access period is not available.';
    END IF;

    SELECT currency_code INTO v_currency_code
    FROM public.subjects
    WHERE id = p_subject_id AND is_active = true;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'The selected subject is not available.';
    END IF;

    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(v_user_id::text, 0)
    );

    SELECT id INTO v_cart_id
    FROM public.carts
    WHERE user_id = v_user_id AND status = 'active'
      AND currency_code = v_currency_code
    ORDER BY created_at LIMIT 1 FOR UPDATE;

    IF v_cart_id IS NULL THEN
        INSERT INTO public.carts (user_id, status, currency_code)
        VALUES (v_user_id, 'active', v_currency_code)
        RETURNING id INTO v_cart_id;
    END IF;

    INSERT INTO public.cart_items (
        cart_id, subject_id, unit_price, currency_code,
        pricing_plan_id, duration_days
    )
    VALUES (
        v_cart_id, p_subject_id, v_plan.price, v_plan.currency_code,
        v_plan.id, v_plan.duration_days
    )
    ON CONFLICT (cart_id, subject_id) DO UPDATE
    SET unit_price = EXCLUDED.unit_price,
        currency_code = EXCLUDED.currency_code,
        pricing_plan_id = EXCLUDED.pricing_plan_id,
        duration_days = EXCLUDED.duration_days;

    UPDATE public.carts SET updated_at = clock_timestamp() WHERE id = v_cart_id;
    RETURN v_cart_id;
END;
$function$;

REVOKE ALL ON FUNCTION public.add_subject_to_cart(bigint, integer)
FROM PUBLIC, anon, service_role;
GRANT EXECUTE ON FUNCTION public.add_subject_to_cart(bigint, integer)
TO authenticated;

CREATE FUNCTION public.get_my_cart_with_plans()
RETURNS TABLE (
    cart_id uuid,
    subject_id bigint,
    subject_code text,
    subject_title text,
    unit_price numeric,
    currency_code text,
    duration_days integer,
    added_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
    v_user_id uuid := auth.uid();
BEGIN
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Sign in to view your cart.';
    END IF;

    RETURN QUERY
    SELECT c.id, s.id::bigint, s.code, s.title, i.unit_price,
        i.currency_code, i.duration_days, i.created_at
    FROM public.carts AS c
    JOIN public.cart_items AS i ON i.cart_id = c.id
    JOIN public.subjects AS s ON s.id = i.subject_id
    WHERE c.user_id = v_user_id AND c.status = 'active'
    ORDER BY i.created_at;
END;
$function$;

REVOKE ALL ON FUNCTION public.get_my_cart_with_plans()
FROM PUBLIC, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_cart_with_plans()
TO authenticated;

COMMENT ON TABLE public.subject_pricing_plans IS
    'Administrator-maintained authoritative access periods and prices for subject practice.';
COMMENT ON FUNCTION public.add_subject_to_cart(bigint, integer) IS
    'Adds or replaces one subject cart item using the server-side pricing plan.';
COMMENT ON FUNCTION public.get_my_cart_with_plans() IS
    'Returns the authenticated cart with server-recorded duration and price.';

NOTIFY pgrst, 'reload schema';
